# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graphics_Operators.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graphics_Operators(object):
    def setupUi(self, Graphics_Operators):
        Graphics_Operators.setObjectName("Graphics_Operators")
        Graphics_Operators.resize(403, 385)
        Graphics_Operators.setMinimumSize(QtCore.QSize(403, 385))
        self.label_2 = QtWidgets.QLabel(Graphics_Operators)
        self.label_2.setGeometry(QtCore.QRect(110, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Graphics_Operators)
        self.label.setGeometry(QtCore.QRect(160, 40, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button_CO = QtWidgets.QPushButton(Graphics_Operators)
        self.button_CO.setGeometry(QtCore.QRect(40, 80, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_CO.setFont(font)
        self.button_CO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_CO.setObjectName("button_CO")
        self.button_DO = QtWidgets.QPushButton(Graphics_Operators)
        self.button_DO.setGeometry(QtCore.QRect(40, 130, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_DO.setFont(font)
        self.button_DO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_DO.setObjectName("button_DO")
        self.button_uniqueSer_CO = QtWidgets.QPushButton(Graphics_Operators)
        self.button_uniqueSer_CO.setGeometry(QtCore.QRect(40, 180, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_uniqueSer_CO.setFont(font)
        self.button_uniqueSer_CO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_uniqueSer_CO.setObjectName("button_uniqueSer_CO")
        self.button_uniqueSer_DO = QtWidgets.QPushButton(Graphics_Operators)
        self.button_uniqueSer_DO.setGeometry(QtCore.QRect(40, 230, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_uniqueSer_DO.setFont(font)
        self.button_uniqueSer_DO.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_uniqueSer_DO.setObjectName("button_uniqueSer_DO")
        self.button_meanOperators = QtWidgets.QPushButton(Graphics_Operators)
        self.button_meanOperators.setGeometry(QtCore.QRect(40, 280, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_meanOperators.setFont(font)
        self.button_meanOperators.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_meanOperators.setObjectName("button_meanOperators")
        self.button_backOperators = QtWidgets.QPushButton(Graphics_Operators)
        self.button_backOperators.setGeometry(QtCore.QRect(40, 330, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_backOperators.setFont(font)
        self.button_backOperators.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_backOperators.setObjectName("button_backOperators")

        self.retranslateUi(Graphics_Operators)
        QtCore.QMetaObject.connectSlotsByName(Graphics_Operators)

    def retranslateUi(self, Graphics_Operators):
        _translate = QtCore.QCoreApplication.translate
        Graphics_Operators.setWindowTitle(_translate("Graphics_Operators", "CIDC Challenge"))
        self.label_2.setText(_translate("Graphics_Operators", "CIDC Challenge"))
        self.label.setText(_translate("Graphics_Operators", "Operators"))
        self.button_CO.setText(_translate("Graphics_Operators", "Considering Outliers"))
        self.button_DO.setText(_translate("Graphics_Operators", "Desconsidering Outliers"))
        self.button_uniqueSer_CO.setText(_translate("Graphics_Operators", "Unique Services Considering Outliers"))
        self.button_uniqueSer_DO.setText(_translate("Graphics_Operators", "Unique Services Desconsidering Outliers"))
        self.button_meanOperators.setText(_translate("Graphics_Operators", "Mean"))
        self.button_backOperators.setText(_translate("Graphics_Operators", "Back"))
