# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Graphics_Menu.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Graphics_Menu(object):
    def setupUi(self, Graphics_Menu):
        Graphics_Menu.setObjectName("Graphics_Menu")
        Graphics_Menu.resize(400, 350)
        Graphics_Menu.setMinimumSize(QtCore.QSize(400, 350))
        self.label_2 = QtWidgets.QLabel(Graphics_Menu)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_2.setFont(font)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Graphics_Menu)
        self.label.setGeometry(QtCore.QRect(50, 40, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.button_operatorsG = QtWidgets.QPushButton(Graphics_Menu)
        self.button_operatorsG.setGeometry(QtCore.QRect(70, 90, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_operatorsG.setFont(font)
        self.button_operatorsG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_operatorsG.setObjectName("button_operatorsG")
        self.button_servicesG = QtWidgets.QPushButton(Graphics_Menu)
        self.button_servicesG.setGeometry(QtCore.QRect(70, 140, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_servicesG.setFont(font)
        self.button_servicesG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_servicesG.setObjectName("button_servicesG")
        self.button_employeesG = QtWidgets.QPushButton(Graphics_Menu)
        self.button_employeesG.setGeometry(QtCore.QRect(70, 190, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_employeesG.setFont(font)
        self.button_employeesG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_employeesG.setObjectName("button_employeesG")
        self.button_backG = QtWidgets.QPushButton(Graphics_Menu)
        self.button_backG.setGeometry(QtCore.QRect(70, 290, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_backG.setFont(font)
        self.button_backG.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_backG.setObjectName("button_backG")
        self.button_histograms = QtWidgets.QPushButton(Graphics_Menu)
        self.button_histograms.setGeometry(QtCore.QRect(70, 240, 271, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.button_histograms.setFont(font)
        self.button_histograms.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_histograms.setObjectName("button_histograms")

        self.retranslateUi(Graphics_Menu)
        QtCore.QMetaObject.connectSlotsByName(Graphics_Menu)

    def retranslateUi(self, Graphics_Menu):
        _translate = QtCore.QCoreApplication.translate
        Graphics_Menu.setWindowTitle(_translate("Graphics_Menu", "CIDC Challenge "))
        self.label_2.setText(_translate("Graphics_Menu", "CIDC Challenge"))
        self.label.setText(_translate("Graphics_Menu", "Building a report trough a spread sheet"))
        self.button_operatorsG.setText(_translate("Graphics_Menu", "Operators Graphics"))
        self.button_servicesG.setText(_translate("Graphics_Menu", "Services Graphics"))
        self.button_employeesG.setText(_translate("Graphics_Menu", "Employees Graphics"))
        self.button_backG.setText(_translate("Graphics_Menu", "Back"))
        self.button_histograms.setText(_translate("Graphics_Menu", "Histograms"))
